name: combine
description: A Flutter package which allows you to work with
  MethodChannels in Isolate and provides simplified Isolate and Thread Pool API.
version: 0.4.0
homepage: https://github.com/Maksimka101/combine
repository: https://github.com/Maksimka101/combine

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  all_lint_rules_community: ^0.0.9
  mocktail: ^0.3.0
  meta: ^1.7.0

flutter:
